### ISSUE TITLE
project board

### ISSUE THREAD

**Issue by r20222** [sannevanseeventer/SPATwater-2.0#11]
Goed dat jullie de Moscow methode hebben gebruikt voor de taken. 👍 
Als het design straks af is dan kun je taken maken van de componenten, dus denk hierbij aan: nav-bar, search-bar, footer, filter opties etc.  Het is handig om bij elke taak een label toe te voegen van welke fase het is van de dev-lifecycle.

**Comment by sannevanseeventer** [comment]
Thanks voor de tip @r20222 , gaan we zeker doen!  :)
